name: security-action
on:
  push:
    branches: [dev]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v4
    - uses: MobileDevOps/flutter-sdk-action@v1.0.0
    - name: build for veracode
      working-directory: ./android/
      run: |
        flutter build apk --debug